import React from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  ImageBackground, StatusBar, Platform,
} from 'react-native';
import MaterialIcons from 'react-native-vector-icons/MaterialIcons';
import { useNavigation } from '@react-navigation/native';

const LAST_UPDATED = 'May 1, 2025';

const SECTIONS = [
  {
    icon: 'handshake',
    title: '1. Acceptance of Terms',
    body: 'By accessing or using AstrataSound ("the App"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the App. We reserve the right to update these terms at any time, and continued use constitutes acceptance of any changes.',
  },
  {
    icon: 'music-note',
    title: '2. Use of the Service',
    body: 'AstrataSound provides an AI-powered music generation platform. You may use the App for personal or commercial purposes subject to your subscription plan. You agree not to use the service for any unlawful purpose, to upload harmful content, or to attempt to reverse-engineer the AI models.',
  },
  {
    icon: 'auto-awesome',
    title: '3. AI-Generated Content',
    body: 'Songs, lyrics, and cover art generated by the AI are unique to each generation. While we strive for originality, we cannot guarantee that AI outputs will not resemble existing works. You are responsible for ensuring your use of generated content complies with applicable laws.',
  },
  {
    icon: 'copyright',
    title: '4. Intellectual Property',
    body: 'You retain ownership of songs you generate within your subscription. AstrataSound retains all rights to the platform, AI models, and underlying technology. Harmony (free) plan users receive a personal-use license only. Melody and Symphony subscribers receive a commercial-use license.',
  },
  {
    icon: 'credit-card',
    title: '5. Payments & Subscriptions',
    body: 'Subscription fees are billed in advance on a monthly or annual basis. All payments are non-refundable unless required by law. Token allocations reset at the start of each billing cycle and do not carry over. You may cancel your subscription at any time; access continues until the period ends.',
  },
  {
    icon: 'block',
    title: '6. Prohibited Conduct',
    body: 'You agree not to: (a) violate any laws; (b) impersonate others; (c) distribute malware; (d) circumvent security measures; (e) scrape or mass-harvest content; (f) use the service to generate content that is illegal, defamatory, or infringes third-party rights.',
  },
  {
    icon: 'gavel',
    title: '7. Termination',
    body: 'We reserve the right to suspend or terminate your account at any time if you violate these terms. Upon termination, your access to the service and any generated content hosted on our servers will cease. You may export your data prior to termination.',
  },
  {
    icon: 'shield',
    title: '8. Disclaimer of Warranties',
    body: 'AstrataSound is provided "as is" without warranties of any kind. We do not guarantee uninterrupted service, error-free operation, or that AI-generated content will meet your specific requirements. Use of the service is at your own risk.',
  },
  {
    icon: 'info',
    title: '9. Contact',
    body: 'For any questions regarding these Terms of Service, please contact us at legal@astratasounds.com.',
  },
];

const TermsScreen = () => {
  const navigation = useNavigation();

  return (
    <ImageBackground source={require('../assets/images/image-1.jpg')} style={s.background} resizeMode="cover">
      <StatusBar translucent backgroundColor="transparent" barStyle="light-content" />

      <View style={s.navBar}>
        <TouchableOpacity style={s.backBtn} onPress={() => navigation.goBack()} activeOpacity={0.8}>
          <MaterialIcons name="arrow-back-ios" size={18} color="#fff" />
        </TouchableOpacity>
        <Text style={s.navTitle}>TERMS OF SERVICE</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>

        {/* Header card */}
        <View style={s.headerCard}>
          <View style={s.headerIconWrap}>
            <MaterialIcons name="gavel" size={32} color="#66cc33" />
          </View>
          <View style={s.headerText}>
            <Text style={s.headerTitle}>Terms of Service</Text>
            <Text style={s.headerSub}>Last updated: {LAST_UPDATED}</Text>
          </View>
        </View>

        <Text style={s.intro}>
          Please read these Terms of Service carefully before using AstrataSound. These terms govern your access to and use of our AI music creation platform.
        </Text>

        {SECTIONS.map((sec) => (
          <View key={sec.title} style={s.sectionCard}>
            <View style={s.sectionHeader}>
              <View style={s.sectionIcon}>
                <MaterialIcons name={sec.icon} size={16} color="#66cc33" />
              </View>
              <Text style={s.sectionTitle}>{sec.title}</Text>
            </View>
            <Text style={s.sectionBody}>{sec.body}</Text>
          </View>
        ))}

        <Text style={s.footer}>© 2025 AstrataSound. All rights reserved.</Text>

      </ScrollView>
    </ImageBackground>
  );
};

export default TermsScreen;

const s = StyleSheet.create({
  background: { flex: 1, width: '100%', height: '100%' },
  navBar: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 58 : (StatusBar.currentHeight ?? 24) + 12,
    paddingBottom: 12,
  },
  backBtn: {
    width: 40, height: 40, borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.1)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center', alignItems: 'center',
  },
  navTitle: { color: '#fff', fontFamily: 'Oswald-Bold', fontSize: 15, letterSpacing: 1.5, flex: 1, textAlign: 'center' },

  scroll: { paddingHorizontal: 16, paddingBottom: 80, paddingTop: 4 },

  headerCard: {
    flexDirection: 'row', alignItems: 'center', gap: 14,
    backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 18,
    borderWidth: 1, borderColor: 'rgba(255,255,255,0.15)',
    padding: 16, marginBottom: 16,
  },
  headerIconWrap: {
    width: 58, height: 58, borderRadius: 17,
    backgroundColor: 'rgba(102,204,51,0.12)', borderWidth: 1, borderColor: 'rgba(102,204,51,0.2)',
    justifyContent: 'center', alignItems: 'center', flexShrink: 0,
  },
  headerText: { flex: 1 },
  headerTitle: { color: '#fff', fontFamily: 'Oswald-Bold', fontSize: 20, marginBottom: 4 },
  headerSub: { color: 'rgba(255,255,255,0.4)', fontFamily: 'Oswald-Regular', fontSize: 12 },

  intro: {
    color: 'rgba(255,255,255,0.55)', fontFamily: 'Oswald-Regular', fontSize: 13, lineHeight: 21,
    marginBottom: 16, paddingHorizontal: 2,
  },

  sectionCard: {
    backgroundColor: 'rgba(255,255,255,0.08)', borderRadius: 14,
    borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)',
    padding: 16, marginBottom: 10,
  },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  sectionIcon: {
    width: 30, height: 30, borderRadius: 9,
    backgroundColor: 'rgba(102,204,51,0.12)', justifyContent: 'center', alignItems: 'center', flexShrink: 0,
  },
  sectionTitle: { color: '#fff', fontFamily: 'Oswald-Bold', fontSize: 14, flex: 1 },
  sectionBody: { color: 'rgba(255,255,255,0.6)', fontFamily: 'Oswald-Regular', fontSize: 13, lineHeight: 20 },

  footer: {
    color: 'rgba(255,255,255,0.25)', fontFamily: 'Oswald-Regular', fontSize: 12, textAlign: 'center', marginTop: 8,
  },
});
