// ── Category map: frontend label → backend enum value ───────
export const CATEGORIES = [
  { label: "Pop", value: "Pop" },
  { label: "Dance Pop", value: "Dance Pop" },
  { label: "Electropop", value: "Electropop" },
  { label: "Synth-pop", value: "Synth-pop" },
  { label: "Dream Pop", value: "Dream Pop" },
  { label: "Indie Pop", value: "Indie Pop" },
  { label: "Bedroom Pop", value: "Bedroom Pop" },
  { label: "Bubblegum Pop", value: "Bubblegum Pop" },
  { label: "Teen Pop", value: "Teen Pop" },
  { label: "Art Pop", value: "Art Pop" },
  { label: "Chamber Pop", value: "Chamber Pop" },
  { label: "Baroque Pop", value: "Baroque Pop" },
  { label: "Power Pop", value: "Power Pop" },
  { label: "City Pop", value: "City Pop" },
  { label: "K-Pop", value: "K-Pop" },
  { label: "J-Pop", value: "J-Pop" },
  { label: "C-Pop", value: "C-Pop" },
  { label: "Mandopop", value: "Mandopop" },
  { label: "Cantopop", value: "Cantopop" },
  { label: "Europop", value: "Europop" },
  { label: "Hip-Hop", value: "Hip-Hop" },
  { label: "Rap", value: "Rap" },
  { label: "Trap", value: "Trap" },
  { label: "Drill", value: "Drill" },
  { label: "UK Drill", value: "UK Drill" },
  { label: "Boom Bap", value: "Boom Bap" },
  { label: "Conscious Hip-Hop", value: "Conscious Hip-Hop" },
  { label: "Gangsta Rap", value: "Gangsta Rap" },
  { label: "Cloud Rap", value: "Cloud Rap" },
  { label: "Emo Rap", value: "Emo Rap" },
  { label: "Mumble Rap", value: "Mumble Rap" },
  { label: "Old School Hip-Hop", value: "Old School Hip-Hop" },
  { label: "Chopped and Screwed", value: "Chopped and Screwed" },
  { label: "Crunk", value: "Crunk" },
  { label: "Grime", value: "Grime" },
  { label: "Phonk", value: "Phonk" },
  { label: "Horrorcore", value: "Horrorcore" },
  { label: "Latin Trap", value: "Latin Trap" },
  { label: "Afro Trap", value: "Afro Trap" },
  { label: "Trap Soul", value: "Trap Soul" },
  { label: "R&B", value: "R&B" },
  { label: "Contemporary R&B", value: "Contemporary R&B" },
  { label: "Neo Soul", value: "Neo Soul" },
  { label: "Soul", value: "Soul" },
  { label: "Motown", value: "Motown" },
  { label: "Funk", value: "Funk" },
  { label: "Quiet Storm", value: "Quiet Storm" },
  { label: "New Jack Swing", value: "New Jack Swing" },
  { label: "Doo-Wop", value: "Doo-Wop" },
  { label: "Southern Soul", value: "Southern Soul" },
  { label: "Blue-Eyed Soul", value: "Blue-Eyed Soul" },
  { label: "Gospel", value: "Gospel" },
  { label: "Southern Gospel", value: "Southern Gospel" },
  { label: "Praise and Worship", value: "Praise and Worship" },
  { label: "Contemporary Christian", value: "Contemporary Christian" },
  { label: "Christian Rock", value: "Christian Rock" },
  { label: "Christian Pop", value: "Christian Pop" },
  { label: "Spiritual", value: "Spiritual" },
  { label: "Negro Spiritual", value: "Negro Spiritual" },
  { label: "Gospel Blues", value: "Gospel Blues" },
  { label: "Rock", value: "Rock" },
  { label: "Classic Rock", value: "Classic Rock" },
  { label: "Hard Rock", value: "Hard Rock" },
  { label: "Soft Rock", value: "Soft Rock" },
  { label: "Alternative Rock", value: "Alternative Rock" },
  { label: "Indie Rock", value: "Indie Rock" },
  { label: "Garage Rock", value: "Garage Rock" },
  { label: "Psychedelic Rock", value: "Psychedelic Rock" },
  { label: "Progressive Rock", value: "Progressive Rock" },
  { label: "Art Rock", value: "Art Rock" },
  { label: "Post-Rock", value: "Post-Rock" },
  { label: "Math Rock", value: "Math Rock" },
  { label: "Southern Rock", value: "Southern Rock" },
  { label: "Blues Rock", value: "Blues Rock" },
  { label: "Folk Rock", value: "Folk Rock" },
  { label: "Surf Rock", value: "Surf Rock" },
  { label: "Glam Rock", value: "Glam Rock" },
  { label: "Grunge", value: "Grunge" },
  { label: "Post-Punk", value: "Post-Punk" },
  { label: "Punk Rock", value: "Punk Rock" },
  { label: "Pop Punk", value: "Pop Punk" },
  { label: "Hardcore Punk", value: "Hardcore Punk" },
  { label: "Emo", value: "Emo" },
  { label: "Screamo", value: "Screamo" },
  { label: "Post-Hardcore", value: "Post-Hardcore" },
  { label: "Krautrock", value: "Krautrock" },
  { label: "Yacht Rock", value: "Yacht Rock" },
  { label: "Stoner Rock", value: "Stoner Rock" },
  { label: "Space Rock", value: "Space Rock" },
  { label: "Rockabilly", value: "Rockabilly" },
  { label: "Heavy Metal", value: "Heavy Metal" },
  { label: "Thrash Metal", value: "Thrash Metal" },
  { label: "Death Metal", value: "Death Metal" },
  { label: "Black Metal", value: "Black Metal" },
  { label: "Doom Metal", value: "Doom Metal" },
  { label: "Sludge Metal", value: "Sludge Metal" },
  { label: "Power Metal", value: "Power Metal" },
  { label: "Symphonic Metal", value: "Symphonic Metal" },
  { label: "Nu Metal", value: "Nu Metal" },
  { label: "Metalcore", value: "Metalcore" },
  { label: "Deathcore", value: "Deathcore" },
  { label: "Progressive Metal", value: "Progressive Metal" },
  { label: "Folk Metal", value: "Folk Metal" },
  { label: "Industrial Metal", value: "Industrial Metal" },
  { label: "Groove Metal", value: "Groove Metal" },
  { label: "Gothic Metal", value: "Gothic Metal" },
  { label: "Viking Metal", value: "Viking Metal" },
  { label: "Speed Metal", value: "Speed Metal" },
  { label: "Grindcore", value: "Grindcore" },
  { label: "Djent", value: "Djent" },
  { label: "EDM", value: "EDM" },
  { label: "House", value: "House" },
  { label: "Deep House", value: "Deep House" },
  { label: "Tech House", value: "Tech House" },
  { label: "Progressive House", value: "Progressive House" },
  { label: "Electro House", value: "Electro House" },
  { label: "Future House", value: "Future House" },
  { label: "Tropical House", value: "Tropical House" },
  { label: "Techno", value: "Techno" },
  { label: "Minimal Techno", value: "Minimal Techno" },
  { label: "Trance", value: "Trance" },
  { label: "Progressive Trance", value: "Progressive Trance" },
  { label: "Psytrance", value: "Psytrance" },
  { label: "Dubstep", value: "Dubstep" },
  { label: "Brostep", value: "Brostep" },
  { label: "Drum and Bass", value: "Drum and Bass" },
  { label: "Jungle", value: "Jungle" },
  { label: "Breakbeat", value: "Breakbeat" },
  { label: "Big Beat", value: "Big Beat" },
  { label: "Electro", value: "Electro" },
  { label: "Synthwave", value: "Synthwave" },
  { label: "Vaporwave", value: "Vaporwave" },
  { label: "Chillwave", value: "Chillwave" },
  { label: "Downtempo", value: "Downtempo" },
  { label: "Ambient", value: "Ambient" },
  { label: "Dark Ambient", value: "Dark Ambient" },
  { label: "IDM", value: "IDM" },
  { label: "Glitch", value: "Glitch" },
  { label: "Future Bass", value: "Future Bass" },
  { label: "Hardstyle", value: "Hardstyle" },
  { label: "Gabber", value: "Gabber" },
  { label: "Bass Music", value: "Bass Music" },
  { label: "Dub", value: "Dub" },
  { label: "Dubtechno", value: "Dubtechno" },
  { label: "Electroclash", value: "Electroclash" },
  { label: "UK Garage", value: "UK Garage" },
  { label: "Speed Garage", value: "Speed Garage" },
  { label: "Trip-Hop", value: "Trip-Hop" },
  { label: "Witch House", value: "Witch House" },
  { label: "Hyperpop", value: "Hyperpop" },
  { label: "Lo-Fi Hip-Hop", value: "Lo-Fi Hip-Hop" },
  { label: "Chillout", value: "Chillout" },
  { label: "Chillhop", value: "Chillhop" },
  { label: "Study Beats", value: "Study Beats" },
  { label: "Bedroom Chill", value: "Bedroom Chill" },
  { label: "Sleep Ambient", value: "Sleep Ambient" },
  { label: "Jazz", value: "Jazz" },
  { label: "Smooth Jazz", value: "Smooth Jazz" },
  { label: "Bebop", value: "Bebop" },
  { label: "Swing", value: "Swing" },
  { label: "Big Band", value: "Big Band" },
  { label: "Cool Jazz", value: "Cool Jazz" },
  { label: "Free Jazz", value: "Free Jazz" },
  { label: "Fusion Jazz", value: "Fusion Jazz" },
  { label: "Latin Jazz", value: "Latin Jazz" },
  { label: "Acid Jazz", value: "Acid Jazz" },
  { label: "Nu Jazz", value: "Nu Jazz" },
  { label: "Gypsy Jazz", value: "Gypsy Jazz" },
  { label: "Dixieland", value: "Dixieland" },
  { label: "Modal Jazz", value: "Modal Jazz" },
  { label: "Hard Bop", value: "Hard Bop" },
  { label: "Blues", value: "Blues" },
  { label: "Delta Blues", value: "Delta Blues" },
  { label: "Chicago Blues", value: "Chicago Blues" },
  { label: "Electric Blues", value: "Electric Blues" },
  { label: "Country Blues", value: "Country Blues" },
  { label: "Piedmont Blues", value: "Piedmont Blues" },
  { label: "Classical", value: "Classical" },
  { label: "Baroque", value: "Baroque" },
  { label: "Romantic Era", value: "Romantic Era" },
  { label: "Contemporary Classical", value: "Contemporary Classical" },
  { label: "Minimalism", value: "Minimalism" },
  { label: "Opera", value: "Opera" },
  { label: "Chamber Music", value: "Chamber Music" },
  { label: "Orchestral", value: "Orchestral" },
  { label: "Choral", value: "Choral" },
  { label: "Avant-Garde Classical", value: "Avant-Garde Classical" },
  { label: "Country", value: "Country" },
  { label: "Country Pop", value: "Country Pop" },
  { label: "Outlaw Country", value: "Outlaw Country" },
  { label: "Bluegrass", value: "Bluegrass" },
  { label: "Americana", value: "Americana" },
  { label: "Folk", value: "Folk" },
  { label: "Contemporary Folk", value: "Contemporary Folk" },
  { label: "Singer-Songwriter", value: "Singer-Songwriter" },
  { label: "Appalachian Folk", value: "Appalachian Folk" },
  { label: "Celtic Folk", value: "Celtic Folk" },
  { label: "Sea Shanty", value: "Sea Shanty" },
  { label: "Honky Tonk", value: "Honky Tonk" },
  { label: "Alt-Country", value: "Alt-Country" },
];

export const TABS = ['Lyrics', 'Cover', 'Generate'];

// Backend values match SongLength in generate-song.dto.ts (a separate concept from
// SongDuration/token pricing — picking a shorter length here never changes price).
// Picking a shorter length doesn't trim an already-generated full song afterward — the
// AI writes a smaller, complete song from scratch (fewer verses, shorter structure) so
// it sounds finished at that length instead of cut off.
export const SONG_LENGTHS = [
    { value: 'short', label: 'Short', sub: '~2 min' },
    { value: 'normal', label: 'Normal', sub: '~3–3:30 min' },
    { value: 'full', label: 'Full', sub: '4+ min' },
];

export const LANGUAGES = [
    { value: 'english', label: 'English', native: 'English', flag: '🇺🇸' },
    { value: 'spanish', label: 'Spanish', native: 'Español', flag: '🇪🇸' },
    { value: 'french',  label: 'French',  native: 'Français', flag: '🇫🇷' },
];

export const MOODS = [
    // Positive / Upbeat
    { value: 'happy',        label: 'Happy',        emoji: '😊', color: '#FFD700' },
    { value: 'uplifting',    label: 'Uplifting',    emoji: '✨', color: '#ffd54f' },
    { value: 'excited',      label: 'Excited',      emoji: '🎉', color: '#ff6f00' },
    { value: 'playful',      label: 'Playful',      emoji: '🎈', color: '#ffee58' },
    { value: 'groovy',       label: 'Groovy',       emoji: '🎸', color: '#f48fb1' },
    // Calm / Peaceful
    { value: 'peaceful',     label: 'Peaceful',     emoji: '🍃', color: '#66cc33' },
    { value: 'calm',         label: 'Calm',         emoji: '🌊', color: '#29b6f6' },
    { value: 'relaxed',      label: 'Relaxed',      emoji: '😌', color: '#80cbc4' },
    { value: 'chill',        label: 'Chill',        emoji: '❄️', color: '#4dd0e1' },
    { value: 'dreamy',       label: 'Dreamy',       emoji: '💭', color: '#ce93d8' },
    // Romantic / Emotional
    { value: 'romantic',     label: 'Romantic',     emoji: '❤️', color: '#ff4d6d' },
    { value: 'love',         label: 'Love',         emoji: '💕', color: '#f06292' },
    { value: 'emotional',    label: 'Emotional',    emoji: '🥺', color: '#e91e63' },
    // Sad / Melancholic
    { value: 'sad',          label: 'Sad',          emoji: '😢', color: '#4fc3f7' },
    { value: 'melancholic',  label: 'Melancholic',  emoji: '🌧️', color: '#9575cd' },
    { value: 'nostalgic',    label: 'Nostalgic',    emoji: '🌅', color: '#ff7043' },
    // Motivational / Inspirational
    { value: 'motivational', label: 'Motivational', emoji: '💪', color: '#f57c00' },
    { value: 'inspirational',label: 'Inspirational',emoji: '🌟', color: '#ffca28' },
    { value: 'hopeful',      label: 'Hopeful',      emoji: '🌈', color: '#42a5f5' },
    { value: 'energetic',    label: 'Energetic',    emoji: '⚡', color: '#ff9800' },
    // Dark / Intense
    { value: 'dark',         label: 'Dark',         emoji: '🌑', color: '#546e7a' },
    { value: 'intense',      label: 'Intense',      emoji: '💥', color: '#c62828' },
    { value: 'dramatic',     label: 'Dramatic',     emoji: '🎭', color: '#7b1fa2' },
    { value: 'aggressive',   label: 'Aggressive',   emoji: '😤', color: '#b71c1c' },
    { value: 'rebellious',   label: 'Rebellious',   emoji: '🔥', color: '#e53935' },
    // Mysterious / Epic
    { value: 'mysterious',   label: 'Mysterious',   emoji: '🌙', color: '#4527a0' },
    { value: 'epic',         label: 'Epic',         emoji: '🏆', color: '#ff8f00' },
    { value: 'cinematic',    label: 'Cinematic',    emoji: '🎬', color: '#1565c0' },
    // Mindful / Spiritual
    { value: 'focused',      label: 'Focused',      emoji: '🎯', color: '#00897b' },
    { value: 'meditative',   label: 'Meditative',   emoji: '🧘', color: '#66bb6a' },
    { value: 'spiritual',    label: 'Spiritual',    emoji: '🕊️', color: '#b39ddb' },
];
