import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    background: { flex: 1 },
    container: { flex: 1 },

    // ── Step indicator ─────────────────────────────────────────
    stepWrap: {
        paddingHorizontal: 24,
        paddingTop: 10,
        paddingBottom: 6,
    },
    stepCircleRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    stepCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepNum: {
        color: 'rgba(255,255,255,0.5)',
        fontFamily: 'Oswald-Bold',
        fontSize: 13,
    },
    stepNumActive: { color: '#fff' },
    stepLine: {
        flex: 1,
        height: 2,
        marginHorizontal: 3,
    },
    stepLabelRow: {
        flexDirection: 'row',
        marginTop: 6,
    },
    stepLabel: {
        width: 42,
        textAlign: 'center',
        color: 'rgba(255,255,255,0.4)',
        fontFamily: 'Oswald-Regular',
        fontSize: 10,
        letterSpacing: 0.3,
        textTransform: 'uppercase',
    },
    stepLabelActive: {
        color: '#66cc33',
        fontFamily: 'Oswald-Bold',
    },
    stepLabelSpacer: { flex: 1 },

    // ── Tab content ────────────────────────────────────────────
    tabContent: { flex: 1 },
    tabContentInner: { paddingHorizontal: 16, paddingBottom: 32 },

    // ── Bottom step nav ────────────────────────────────────────
    bottomNav: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255,255,255,0.08)',
        backgroundColor: 'rgba(0,0,0,0.2)',
        gap: 10,
    },
    prevBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: 'rgba(255,255,255,0.08)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.12)',
    },
    prevBtnText: {
        color: 'rgba(255,255,255,0.65)',
        fontFamily: 'Oswald-Bold',
        fontSize: 13,
        letterSpacing: 0.5,
    },
    nextBtn: {
        flex: 1,
        borderRadius: 12,
        overflow: 'hidden',
    },
    nextBtnGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        // paddingVertical: 13,
    },
    nextBtnText: {
        color: '#fff',
        fontFamily: 'Oswald-Bold',
        fontSize: 14,
        letterSpacing: 0.5,
        paddingVertical:18
    },

    // ── Section labels ─────────────────────────────────────────
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
        marginTop: 6,
    },
    sectionLabelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
        marginTop: 14,
    },
    sectionLabelLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    sectionIconWrap: {
        width: 24,
        height: 24,
        borderRadius: 7,
        backgroundColor: 'rgba(102,204,51,0.15)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    sectionLabelText: {
        color: '#fff',
        fontSize: 14,
        fontFamily: 'Oswald-Bold',
        letterSpacing: 0.5,
    },
    hintBtn: { padding: 4 },
    instrumentalRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    instrumentalLabel: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 12,
        fontFamily: 'Oswald-Regular',
    },

    // ── Glass box ──────────────────────────────────────────────
    glassBox: {
        backgroundColor: 'rgba(255,255,255,0.07)',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.15)',
        padding: 14,
        marginBottom: 4,
    },
    textArea: {
        color: '#fff',
        fontSize: 14,
        fontFamily: 'Oswald-Regular',
        textAlignVertical: 'top',
        minHeight: 70,
    },
    charCount: {
        color: 'rgba(255,255,255,0.35)',
        fontSize: 10,
        textAlign: 'right',
        marginTop: 6,
        fontFamily: 'Oswald-Regular',
    },

    // ── Style mode toggle ──────────────────────────────────────
    styleModeRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
    styleModeBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        backgroundColor: 'rgba(255,255,255,0.07)',
        borderRadius: 12,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.12)',
    },
    styleModeBtnActive: {
        backgroundColor: 'rgba(102,204,51,0.12)',
        borderColor: 'rgba(102,204,51,0.4)',
    },
    styleModeVibeActive: {
        backgroundColor: 'rgba(4,126,201,0.12)',
        borderColor: 'rgba(4,126,201,0.4)',
    },
    styleModeBtnText: {
        color: 'rgba(255,255,255,0.45)',
        fontFamily: 'Oswald-Bold',
        fontSize: 12,
    },
    styleModeBtnTextActive: { color: '#66cc33' },
    styleModeBtnTextVibe: { color: '#047ec9' },

    // ── Category horizontal scroll ─────────────────────────────
    categoryScroll: { marginTop: 10, marginBottom: 2 },
    categoryScrollContent: { flexDirection: 'row', gap: 8, paddingRight: 8 },
    tag: {
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderRadius: 20,
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    tagActive: {
        backgroundColor: '#66cc33',
        borderColor: '#66cc33',
        shadowColor: '#66cc33',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.45,
        shadowRadius: 6,
        elevation: 4,
    },
    tagText: {
        color: 'rgba(255,255,255,0.75)',
        fontSize: 12,
        fontFamily: 'Oswald-Bold',
    },
    tagTextActive: { color: '#fff' },

    // ── Vibe picker ────────────────────────────────────────────
    vibeLoadingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingVertical: 16,
    },
    vibeLoadingText: {
        color: 'rgba(255,255,255,0.5)',
        fontFamily: 'Oswald-Regular',
        fontSize: 13,
    },
    vibeEmptyBox: {
        alignItems: 'center',
        gap: 8,
        paddingVertical: 24,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        backgroundColor: 'rgba(255,255,255,0.04)',
    },
    vibeEmptyText: {
        color: 'rgba(255,255,255,0.35)',
        fontFamily: 'Oswald-Regular',
        fontSize: 12,
        textAlign: 'center',
        paddingHorizontal: 20,
    },
    vibePickCard: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        backgroundColor: 'rgba(255,255,255,0.06)',
        borderRadius: 14,
        padding: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        marginBottom: 8,
    },
    vibePickCardActive: {
        backgroundColor: 'rgba(4,126,201,0.12)',
        borderColor: 'rgba(4,126,201,0.4)',
    },
    vibePickDot: { width: 10, height: 10, borderRadius: 5 },
    vibePickName: {
        color: 'rgba(255,255,255,0.7)',
        fontFamily: 'Oswald-Bold',
        fontSize: 14,
    },
    vibePickMeta: {
        color: 'rgba(255,255,255,0.4)',
        fontFamily: 'Oswald-Regular',
        fontSize: 11,
        marginTop: 2,
    },

    // ── Lyrics AI mode ─────────────────────────────────────────
    aiLyricsSelected: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: 'rgba(102,204,51,0.1)',
        borderRadius: 10,
        padding: 10,
        marginBottom: 8,
    },
    aiLyricsSelectedText: {
        flex: 1,
        color: '#66cc33',
        fontFamily: 'Oswald-Bold',
        fontSize: 13,
    },
    aiLyricsClear: { padding: 4 },

    // ── AI button ──────────────────────────────────────────────
    aiBtn: {
        marginTop: 10,
        alignSelf: 'flex-start',
        borderRadius: 20,
        overflow: 'hidden',
    },
    aiBtnGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(102,204,51,0.35)',
    },
    aiBtnText: {
        color: '#66cc33',
        fontSize: 12,
        fontFamily: 'Oswald-Bold',
        letterSpacing: 0.5,
        padding: 10,
    },

    // ── Gender buttons ─────────────────────────────────────────
    genderRow: { flexDirection: 'row', gap: 10, marginBottom: 4 },
    genderBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255,255,255,0.08)',
        borderRadius: 12,
        paddingVertical: 11,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.15)',
        gap: 4,
    },
    genderBtnActive: {
        backgroundColor: '#66cc33',
        borderColor: '#66cc33',
        shadowColor: '#66cc33',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
        elevation: 5,
    },
    genderBtnText: {
        color: 'rgba(255,255,255,0.6)',
        fontSize: 13,
        fontFamily: 'Oswald-Bold',
    },
    genderBtnTextActive: { color: '#fff' },
    langNativeText: {
        color: 'rgba(255,255,255,0.55)',
        fontSize: 10,
        fontFamily: 'Oswald-Regular',
        textAlign: 'center',
        marginTop: 1,
    },

    // ── Cover tab ──────────────────────────────────────────────
    coverHeaderCard: {
        marginBottom: 14,
        marginTop: 6,
        borderRadius: 16,
        overflow: 'hidden',
    },
    coverHeaderGrad: {
        paddingVertical: 20,
        alignItems: 'center',
        gap: 8,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
    },
    coverHeaderTitle: {
        color: '#fff',
        fontSize: 18,
        fontFamily: 'Oswald-Bold',
        letterSpacing: 0.5,
    },
    coverHeaderSub: {
        color: 'rgba(255,255,255,0.5)',
        fontSize: 13,
        fontFamily: 'Oswald-Regular',
        textAlign: 'center',
        marginHorizontal: 20,
    },
    aiCoverNote: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 8,
        marginBottom: 4,
    },
    aiCoverNoteText: {
        color: 'rgba(255,255,255,0.35)',
        fontFamily: 'Oswald-Regular',
        fontSize: 11,
        flex: 1,
    },
    uploadCoverBtn: {
        borderRadius: 16,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(4,126,201,0.3)',
        height: 200,
        position: 'relative',
    },
    uploadCoverPreview: { width: '100%', height: '100%' },
    uploadCoverEmpty: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 10,
    },
    uploadCoverEmptyText: {
        color: '#047ec9',
        fontFamily: 'Oswald-Bold',
        fontSize: 15,
    },
    uploadCoverEmptySub: {
        color: 'rgba(255,255,255,0.35)',
        fontFamily: 'Oswald-Regular',
        fontSize: 11,
    },
    uploadCoverChangeOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        backgroundColor: 'rgba(0,0,0,0.55)',
        paddingVertical: 10,
    },
    uploadCoverChangeText: {
        color: '#fff',
        fontFamily: 'Oswald-Bold',
        fontSize: 13,
    },

    // ── Generate tab ───────────────────────────────────────────
    genHeroCard: {
        borderRadius: 18,
        alignItems: 'center',
        gap: 8,
        marginBottom: 6,
        marginTop: 6,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.08)',
        overflow: 'hidden',
    },
    genHeroGrad: {
        width: '100%',
        alignItems: 'center',
        paddingVertical: 20,
        gap: 8,
    },
    genHeroIconWrap: {
        width: 56,
        height: 56,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(102,204,51,0.15)',
        borderWidth: 1,
        borderColor: 'rgba(102,204,51,0.25)',
    },
    genHeroTitle: {
        color: '#fff',
        fontSize: 20,
        fontFamily: 'Oswald-Bold',
        letterSpacing: 0.5,
    },
    genHeroSub: {
        color: 'rgba(255,255,255,0.5)',
        fontFamily: 'Oswald-Regular',
        fontSize: 13,
        textAlign: 'center',
        paddingHorizontal: 20,
    },
    summaryCard: {
        backgroundColor: 'rgba(255,255,255,0.06)',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        padding: 16,
        marginBottom: 4,
    },
    summaryRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    summaryIcon: {
        width: 28,
        height: 28,
        borderRadius: 8,
        backgroundColor: 'rgba(102,204,51,0.12)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    summaryLabel: {
        color: 'rgba(255,255,255,0.4)',
        fontFamily: 'Oswald-Regular',
        fontSize: 12,
        width: 76,
    },
    summaryValue: {
        flex: 1,
        color: '#fff',
        fontFamily: 'Oswald-Bold',
        fontSize: 13,
    },
    summaryDivider: {
        height: 1,
        backgroundColor: 'rgba(255,255,255,0.06)',
        marginVertical: 10,
    },
    summaryStatusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },

    // ── Create button ──────────────────────────────────────────
    createBtnWrap: { marginTop: 20, marginBottom: 16 },
    createBtn: {
        flexDirection: 'row',
        height: 58,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#66cc33',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.45,
        shadowRadius: 14,
        elevation: 10,
    },
    createBtnText: {
        color: '#fff',
        fontSize: 18,
        fontFamily: 'Oswald-Bold',
        letterSpacing: 2,
    },

    // ── Mood picker modal ──────────────────────────────────────
    moodOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.75)',
        justifyContent: 'flex-end',
    },
    moodSheet: {
        backgroundColor: '#0d1117',
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        padding: 24,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    moodHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 6,
    },
    moodHeaderTitle: {
        flex: 1,
        color: '#fff',
        fontFamily: 'Oswald-Bold',
        fontSize: 18,
    },
    moodCloseBtn: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: 'rgba(255,255,255,0.08)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    moodHeaderSub: {
        color: 'rgba(255,255,255,0.4)',
        fontFamily: 'Oswald-Regular',
        fontSize: 12,
        marginBottom: 18,
    },
    moodGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    moodCard: {
        width: (width - 48 - 30) / 4,
        borderRadius: 14,
        overflow: 'hidden',
    },
    moodCardGrad: {
        alignItems: 'center',
        gap: 6,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    moodEmoji: { fontSize: 22, marginTop: 8 },
    moodLabel: { fontFamily: 'Oswald-Bold', fontSize: 10, letterSpacing: 0.5, marginBottom: 8 },

    // ── Generating overlay ─────────────────────────────────────
    genOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 999 },
    genOverlayInner: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 16,
    },
    genSpinWrap: { marginBottom: 8 },
    genSpinGrad: {
        width: 80,
        height: 80,
        borderRadius: 40,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#66cc33',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 20,
        elevation: 12,
    },
    genTitle: {
        color: '#fff',
        fontFamily: 'Oswald-Bold',
        fontSize: 22,
        letterSpacing: 0.5,
    },
    genStep: {
        color: 'rgba(255,255,255,0.6)',
        fontFamily: 'Oswald-Regular',
        fontSize: 14,
        textAlign: 'center',
        lineHeight: 20,
    },
    genDots: { flexDirection: 'row', gap: 8, marginTop: 8 },
    genDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#66cc33' },

    // ── Cover art purchase note (Spark plan) ──────────────────
    aiCoverPurchaseNote: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 8,
        backgroundColor: 'rgba(251,191,36,0.08)',
        borderRadius: 10,
        padding: 10,
        marginTop: 8,
        borderWidth: 1,
        borderColor: 'rgba(251,191,36,0.2)',
    },
    aiCoverPurchaseNoteText: {
        flex: 1,
        color: '#FBBF24',
        fontSize: 11,
        fontFamily: 'Oswald-Regular',
        lineHeight: 16,
    },

    // ── Duration picker ────────────────────────────────────────
    durationRow: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 8,
    },
    durationCard: {
        flex: 1,
        backgroundColor: 'rgba(255,255,255,0.06)',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        alignItems: 'center',
        padding: 10,
        paddingBottom: 12,
    },
    durationCardSelected: {
        borderColor: 'rgba(102,204,51,0.6)',
        backgroundColor: 'rgba(102,204,51,0.1)',
    },
    durationCardAffordable: {
        opacity: 0.55,
    },
    durationIconWrap: {
        width: 36,
        height: 36,
        borderRadius: 10,
        backgroundColor: 'rgba(255,255,255,0.08)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 6,
    },
    durationIconWrapSelected: {
        backgroundColor: 'rgba(102,204,51,0.25)',
    },
    durationLabel: {
        color: 'rgba(255,255,255,0.6)',
        fontSize: 12,
        fontFamily: 'Oswald-Bold',
        letterSpacing: 0.3,
        textAlign: 'center',
    },
    durationLabelSelected: {
        color: '#fff',
    },
    durationDesc: {
        color: 'rgba(255,255,255,0.3)',
        fontSize: 9,
        fontFamily: 'Oswald-Regular',
        textAlign: 'center',
        marginTop: 2,
        marginBottom: 6,
    },
    durationCostBadge: {
        backgroundColor: 'rgba(255,255,255,0.08)',
        borderRadius: 6,
        paddingHorizontal: 6,
        paddingVertical: 2,
    },
    durationCostBadgeSelected: {
        backgroundColor: 'rgba(102,204,51,0.2)',
    },
    durationCostText: {
        color: 'rgba(255,255,255,0.4)',
        fontSize: 9,
        fontFamily: 'Oswald-Bold',
        letterSpacing: 0.5,
    },
    durationCostTextSelected: {
        color: '#66cc33',
    },
    durationLockedBadge: {
        position: 'absolute',
        top: 6,
        right: 6,
    },

    // ── Credit balance indicator ───────────────────────────────
    creditBalanceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        marginBottom: 12,
        paddingHorizontal: 2,
    },
    creditBalanceText: {
        fontSize: 11,
        fontFamily: 'Oswald-Regular',
        flex: 1,
    },
});
